- Changelog.md
- INSTALL_WINDOWS.md
- README.md
- doc/header.html
- doc/mainpage.html
- src/NodeShared.cc
Signed-off-by: Louise Poubel <louise@openrobotics.org>
> [ign-transport1] Update BitBucket links

- .github/CODEOWNERS
- .github/workflows/ci-bionic.yml
- .github/workflows/pr-collection-labeler.yml
- .github/workflows/triage.yml
- README.md
- codecov.yml
* Add [labeler workflow](https://github.com/ignition-tooling/pr-collection-labeler)
* Add [triage workflow](https://github.com/marketplace/actions/create-project-card-action)
* Add [Ubuntu CI workflow with Codecov upload](https://github.com/ignition-tooling/ubuntu-bionic-ci-action)
* Update badges
* Add `CODEOWNERS`
> [ign-transport7] Workflow updates

- .github/CODEOWNERS
- .github/workflows/ci-bionic.yml
- .github/workflows/pr-collection-labeler.yml
- .github/workflows/triage.yml
- README.md
- codecov.yml
* Add [labeler workflow](https://github.com/ignition-tooling/pr-collection-labeler)
* Add [triage workflow](https://github.com/marketplace/actions/create-project-card-action)
* Add [Ubuntu CI workflow with Codecov upload](https://github.com/ignition-tooling/ubuntu-bionic-ci-action)
* Update badges
* Add `CODEOWNERS`
> [ign-transport8] Workflow updates

- .github/CODEOWNERS
- .github/workflows/ci-bionic.yml
- .github/workflows/pr-collection-labeler.yml
- .github/workflows/triage.yml
- README.md
- codecov.yml
* Add [labeler workflow](https://github.com/ignition-tooling/pr-collection-labeler)
* Add [triage workflow](https://github.com/marketplace/actions/create-project-card-action)
* Add [Ubuntu CI workflow with Codecov upload](https://github.com/ignition-tooling/ubuntu-bionic-ci-action)
* Update badges
* Add `CODEOWNERS`
> [master] Workflow updates

- .github/CODEOWNERS
- .github/workflows/ci-bionic.yml
- .github/workflows/pr-collection-labeler.yml
- .github/workflows/triage.yml
- README.md
- codecov.yml
* Add [labeler workflow](https://github.com/ignition-tooling/pr-collection-labeler)
* Add [triage workflow](https://github.com/marketplace/actions/create-project-card-action)
* Add [Ubuntu CI workflow with Codecov upload](https://github.com/ignition-tooling/ubuntu-bionic-ci-action)
* Update badges
* Add `CODEOWNERS`
> [ign-transport4] Workflow updates

- tutorials/04_messages.md
- tutorials/05_services.md
- tutorials/07_relay.md
- tutorials/10_logging.md
> download link

- docker/ign-transport/Dockerfile
Signed-off-by: mohamedsayed18 <mohamed95.a.s@gmail.com>
> link to repo

- BUILD.bazel
- log/BUILD.bazel
- log/test/BUILD.bazel
- test/BUILD.bazel
Signed-off-by: John Shepherd <john@openrobotics.org>
> [Bazel] Init attempt at bazel build

- BUILD.bazel
Signed-off-by: John Shepherd <john@openrobotics.org>
> [Bazel] Add uuid and sqlite3 linking flags

- BUILD.bazel
- log/BUILD.bazel
Signed-off-by: John Shepherd <john@openrobotics.org>
> Add export gens

- README.md
Signed-off-by: ahcorde <ahcorde@gmail.com>
> Removed markdown-header

- CMakeLists.txt
- Changelog.md
> 8.1.0 prep

- CMakeLists.txt
- log/test/integration/playback.cc
- log/test/integration/recorder.cc
- src/ign_TEST.cc
- test/integration/twoProcsPubSub.cc
All tests should pass now.
:green_circle:
> Disable flaky Mac OS X tests

- CMakeLists.txt
Diff from `pre1`: https://github.com/ignitionrobotics/ign-transport/compare/ignition-transport9_9.0.0-pre1...master
> ⬆️  9.0.0~pre2

- README.md
The tutorial link now points to `9.0`.
> Update link to the tutorials

- tutorials/20_env_variables.md
- tutorials/21_contribute.md
- tutorials/22_development.md
This is already in the `README.md` file.
> Remove contribute tutorial

- Migration.md
> Add migration notes.

- log/src/Descriptor.cc
- log/src/cmd/LogCommandAPI.cc
This PR is meant to resolve new codecheck issues introduced by https://github.com/ignitionrobotics/ign-cmake/pull/117.
From my understanding, the plan is to forward port the fixes here to all other ignition versions once https://github.com/ignitionrobotics/ign-cmake/pull/117 is merged.
Signed-off-by: Ashton Larkin <ashton@openrobotics.org>
> Resolve updated codecheck issues

- Changelog.md
We were missing some changelog entries.
> 7 to 8 20200105

- Changelog.md
Merges ign-transport8 into ign-transport9 and prepares for 9.1.0 release.
> 9 1 0 prep

- .github/ci/packages.apt
- CMakeLists.txt
- configure.bat
- docker/ign-transport/Dockerfile
Addresses https://github.com/ignition-tooling/release-tools/issues/362
> Bump in edifice: ign-msgs7

- CMakeLists.txt
I believe the `pre1` release was triggered from a different branch. I'll just push this and retrigger the release and upload a new tag.
> 🎈 10.0.0~pre2

- README.md
- tutorials/02_installation.md
Updates some documentation links in preparation for 10.0 release.
Closes #<NUMBER>
Port <FROM_BRANCH> to <TO_BRANCH>
Branch comparison: https://github.com/ignitionrobotics/<REPO>/compare/<TO_BRANCH>...<FROM_BRANCH>
Preparation for <X.Y.Z> release.
Comparison to <x.y.z>: https://github.com/ignitionrobotics/<REPO>/compare/<LATEST_TAG_BRANCH>...<RELEASE_BRANCH>
**Note to maintainers**: Remember to use …
> Prepare documentation for 10.0 release.

- .github/ci/packages.apt
- CMakeLists.txt
- docker/ign-transport/Dockerfile
See https://github.com/ignition-tooling/release-tools/issues/428
> Bumps in fortress : ign-transport11

- include/ignition/transport/Publisher.hh
- src/Publisher.cc
#240 but for ign-transport10 to see if it breaks ABI.
> Remove unnecessary copy and assignment operators

- src/Discovery.cc
- src/NodeShared.cc
- src/NodeSharedPrivate.hh
Forward port. Fixes zmq deprecation warning.
> 8 :arrow_right: 9 fix homebrew warning

- .github/ci/packages.apt
- CMakeLists.txt
- docker/ign-transport/Dockerfile
See https://github.com/ignition-tooling/release-tools/issues/554
> Bumps in garden : ci_matching_branch/bump_garden_ign-transport12

- tutorials/20_env_variables.md
Signed-off-by: Martin Pecka <peckama2@fel.cvut.cz>
**Closes**: many searches of the docs to figure out whether it is `<HOSTNAME>:<USERNAME>` or `<USERNAME>:<HOSTNAME>` :)
> Documented the default value of IGN_PARTITION

- .github/ci/packages.apt
- bitbucket-pipelines.yml
- docker/ign-transport/Dockerfile
See https://github.com/ignition-tooling/release-tools/issues/574
> Bumps in garden: use ign-math7

- .github/ci/packages.apt
- CMakeLists.txt
- docker/ign-transport/Dockerfile
- tutorials/02_installation.md
See https://github.com/ignition-tooling/release-tools/issues/685
> Bumps in garden : ign-transport12

- Changelog.md
- conf/transport.yaml.in
- example/configure.bat
- example/playback.cc
- example/record.cc
- log/src/cmd/cmdlog.rb.in
- log/src/cmd/transportlog.yaml.in
- tutorials/02_installation.md
https://github.com/gazebo-tooling/release-tools/issues/718
> Migrate ignition-transport

- Migration.md
- example/publisher_c.cc
- example/publisher_c_fast.cc
- example/subscriber_c.cc
- example/subscriber_c_slow.cc
- include/gz/transport/CIface.h
- include/gz/transport/TopicStatistics.hh
- include/gz/transport/gz_auto_headers.hh.in
- src/CIface.cc
- src/CIface_TEST.cc
- src/Clock_TEST.cc
- tutorials/04_messages.md
- tutorials/05_services.md
- tutorials/10_logging.md
See: https://github.com/gazebo-tooling/release-tools/issues/767
> ign -> gz Provisional Finale: Source Migration : gz-transport

- CMakeLists.txt
- api.md.in
- conf/CMakeLists.txt
- include/ignition/transport/CMakeLists.txt
- include/ignition/transport/config.hh.in
- include/ignition/transport/ign_auto_headers.hh.in
- src/cmd/CMakeLists.txt
- test/integration/all_symbols_have_version.bash.in
- tutorials.md.in
I ran `find . -name "*" -exec -i 's/IGN_DESIGNATION/GZ_DESIGNATION/g' {} \;` in order to make this repository compliant with https://github.com/gazebosim/gz-cmake/pull/282
> Change IGN_DESIGNATION to GZ_DESIGNATION

- CMakeLists.txt
- api.md.in
- conf/CMakeLists.txt
- include/ignition/transport/CMakeLists.txt
- include/ignition/transport/config.hh.in
- include/ignition/transport/ign_auto_headers.hh.in
- src/cmd/CMakeLists.txt
- test/integration/all_symbols_have_version.bash.in
- tutorials.md.in
This merges forward GZ_DESIGNATION updates from v6 to v7.
> 6 to 7 GZ_DESIGNATION

- CMakeLists.txt
- Changelog.md
- README.md
- src/Discovery_TEST.cc
- src/cmd/CMakeLists.txt
- src/cmd/gz_TEST.cc
- src/cmd/transport.bash_completion.sh
Port `ign-transport11 ` ➡️  `main`
Branch comparision: https://github.com/ignitionrobotics/ign-transport/compare/main...ign-transport11
> Merge ign-transport11 ➡️  main

- tutorials/04_messages.md
- tutorials/05_services.md
- tutorials/07_relay.md
- tutorials/10_logging.md
- tutorials/23_topic_statistics.md
Some tutorials (like [this one](https://gazebosim.org/api/transport/12/services.html)) recommend the user to download examples and compile them. We were downloading examples and `CMakeLists.txt` files from `main`. `main` is already in version `gz-transport13`, so the examples won't compile.
> Download examples matching the version number

- docker/gz-transport/Dockerfile
- tutorials/07_relay.md
I was testing the [relay tutorial ](https://gazebosim.org/api/transport/12/relay.html) and there's a step where we build a Docker image. `tzdata` hangs during the Docker image build. I tweaked the steps to avoid the hang. Also, we were cloning `gz-transport` main and we should clone `gz-transport12`. 
> Fix Docker build and relay tutorial instructions

- tutorials/02_installation.md
The installation tutorial has a link pointing the previous version. This patch should fix it.
> Update documentation link in the installation tutorial

- tutorials/02_installation.md
Signed-off-by: ahcorde <ahcorde@gmail.com>
Improved instructions. Related https://github.com/gazebosim/garden-tutorial-party/issues/1759
> Improved instructions

- tutorials/04_messages.md
- tutorials/05_services.md
- tutorials/06_security.md
- tutorials/10_logging.md
Signed-off-by: ahcorde <ahcorde@gmail.com>
Improved windows instructions
> Improved windows instructions

- example/publisher_c_fast.cc
- include/gz/transport/Discovery.hh
Remove some warnings on Ubuntu 22.04.
> Remove warnings in Garden and Ubuntu 22.04

- CMakeLists.txt
- Changelog.md
Preparation for 11.3.2 release.
Comparison to 11.3.1: https://github.com/ignitionrobotics/ign-transport/compare/ignition-transport11_11.3.1...ign-transport11
> Prepare for 11.3.2 Release

- CMakeLists.txt
Preparation for 12.1.0 prerelease1.
Comparison to 12.1.0: https://github.com/gazebosim/gz-transport/compare/gz-transport12_12.0.0...gz-transport12
Requires: https://github.com/gazebo-release/gz-transport12-release/pull/18
> 12.1.0 prerelease 1

- Changelog.md
- include/gz/transport/Node.hh
- include/gz/transport/detail/Node.hh
Port ign-transport8 to ign-transport11
Branch comparison: https://github.com/gazebosim/gz-transport/compare/ign-transport11...ign-transport8
> Forward port 8 to 11

- Changelog.md
- example/CMakeLists.txt
- example/requester_raw.cc
- include/gz/transport/Node.hh
- include/gz/transport/detail/Node.hh
- log/test/integration/ChirpParams.hh
- parameters/include/gz/transport/parameters/Client.hh
- parameters/include/gz/transport/parameters/Registry.hh
- parameters/src/Utils.hh
- src/Node.cc
- src/Node_TEST.cc
- src/cmd/gz_src_TEST.cc
- test/integration/authPubSub.cc
- test/integration/authPubSubSubscriberInvalid_aux.cc
- test/integration/fastPub_aux.cc
Port ign-transport11 to gz-transport12
Branch comparison: https://github.com/gazebosim/gz-transport/compare/gz-transport12...ign-transport11
> Forward port 11 to 12

- CMakeLists.txt
- include/gz/transport/Discovery.hh
- include/gz/transport/RepHandler.hh
- include/gz/transport/SubscriptionHandler.hh
- src/cmd/gz.cc
Port `ign-transport8 ` ➡️  `ign-transport11`
Branch comparison: https://github.com/ignitionrobotics/ign-transport/compare/ign-transport11...ign-transport8
> Merge ign-transport8 ➡️  ign-transport11

- CMakeLists.txt
- include/gz/transport/RepHandler.hh
- include/gz/transport/SubscriptionHandler.hh
- src/cmd/gz.cc
Port `gz-transport12 ` ➡️  `main`
Branch comparison: https://github.com/ignitionrobotics/ign-transport/compare/main...gz-transport12
> Merge gz-transport12 ➡️  main

- CMakeLists.txt
- include/gz/transport/Discovery.hh
Port `ign-transport11 ` ➡️  `gz-transport12`
Branch comparison: https://github.com/gazebosim/gz-transport/compare/gz-transport12...ign-transport11
> Merge ign-transport11 ➡️  gz-transport12

- tutorials/02_installation.md
Minor fix in the installation tutorial.
> Fix typo in installation tutorial

- Changelog.md
Port gz-transport12 to gz-transport13
Branch comparison: https://github.com/gazebosim/gz-transport/compare/gz-transport13...gz-transport12
> Merge: 12 -> 13

- tutorials/02_installation.md
Fixes https://github.com/gazebosim/gazebo_test_cases/issues/915
Python tests require `make install`.
> Update installation instruction regarding python tests

- CMakeLists.txt
- Changelog.md
- README.md
- docker/gz-transport/Dockerfile
- example/publisher.cc
- example/subscriber.cc
- python/src/__init__.py
- tutorials/02_installation.md
- tutorials/04_messages.md
- tutorials/05_services.md
- tutorials/07_relay.md
- tutorials/10_logging.md
- tutorials/23_topic_statistics.md
Port gz-transport13 to main
Branch comparison: https://github.com/gazebosim/gz-transport/compare/main...gz-transport13
> Merge: 13 -> main

- CMakeLists.txt
Preparation for 13.2.0~pre2 release.
Comparison to 13.2.0-pre1: https://github.com/gazebosim/gz-transport/compare/gz-transport13_13.2.0-pre1...gz-transport13
> Prepare for 13.2.0~pre2 Release

- Changelog.md
- conf/CMakeLists.txt
- include/gz/transport/NodeShared.hh
- log/src/Recorder.cc
- log/src/cmd/CMakeLists.txt
- parameters/src/cmd/CMakeLists.txt
- src/Node.cc
- src/NodePrivate.hh
- src/NodeShared.cc
- src/cmd/CMakeLists.txt
Port `gz-transport13 ` ➡️  `main`
Branch comparison: https://github.com/gazebosim/gz-transport/compare/main...gz-transport13
> Merge gz-transport13 ➡️  main

- include/gz/transport/Discovery.hh
Updated comment and error msg.
> IGN_IP -> GZ_IP

- log/test/integration/playback.cc
Port ign-transport8 to ign-transport11
Follow up of #517 
Disables #195 
Branch comparison: https://github.com/gazebosim/gz-transport/compare/ign-transport11...ign-transport8
> 8 :arrow_right: 11

- tutorials/06_python_support.md
Fixes some version issues found in the Python tutorial.
> Ionic: Python tutorial updates

- tutorials/06_python_support.md
Fixes #1543
Fixing the below issues with the code snippets in the python tutorial:
- The code provided in the tutorial needs minor change
- Code excerpt needs minor change
> Python tutorial code snippet updates

- tutorials/02_installation.md
Fixes #<NUMBER>
Closes #<NUMBER>
Port <FROM_BRANCH> to <TO_BRANCH>
Branch comparison: https://github.com/gazebosim/<REPO>/compare/<TO_BRANCH>...<FROM_BRANCH>
Preparation for <X.Y.Z> release.
Comparison to <x.y.z>: …
> fix prerequisites windows

- tutorials/06_python_support.md
Fixes https://github.com/gazebosim/gazebo_test_cases/issues/1545
Fixed tutorial snippet so that it works out of the box
> tutorials/06_python_support: Fix tutorial snippet

- include/gz/transport/Publisher.hh
Removed an unused forward declaration.
> Remove unused MessagePublisherPrivate forward declaration

- .github/ci/before_cmake.sh
- .github/ci/packages-noble.apt
Fixes #<NUMBER>
Install additional `ros-jazzy-ros-environment` package so users can take a more ROS-friendly way of setting up ROS env by sourcing the setup.bash script, see https://github.com/gazebo-tooling/release-tools/pull/1311#issuecomment-2883143390
> Install additional ROS package for setting up ROS env

- .github/workflows/bazel.yml
- MODULE.bazel
- log/include/gz/transport/log/Playback.hh
- parameters/src/Utils.hh
- parameters/src/cmd/ParamCommandAPI.cc
Port gz-transport14 to main
Branch comparison: https://github.com/gazebosim/gz-transport/compare/main...gz-transport14
> Merge 14 -> main

- include/gz/transport/ReqHandler.hh
- include/gz/transport/detail/Node.hh
- log/test/integration/playback.cc
- log/test/integration/query.cc
- log/test/integration/recorder.cc
- src/Discovery.hh
- src/NodeShared.cc
- src/Node_TEST.cc
- src/ReqHandler.cc
- test/integration/twoProcsSrvCall.cc
This PR fixes some issues with services that allows us to enable more tests.
The tests should pass.
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.**
> Zenoh - Part8: Fix some service issues and enable more tests

- Changelog.md
- src/NodeShared.cc
Port gz-transport13 to gz-transport14
Branch comparison: https://github.com/gazebosim/gz-transport/compare/gz-transport14...gz-transport13
> Merge 13->14

- tutorials/01_intro.md
- tutorials/04_messages.md
- tutorials/05_services.md
- tutorials/06_python_support.md
- tutorials/07_security.md
- tutorials/08_relay.md
- tutorials/10_logging.md
- tutorials/20_env_variables.md
- tutorials/22_development.md
- tutorials/23_topic_statistics.md
Adds some documentation about Zenoh.
```
cd ~/jetty_ws/build/gz-transport
make doc
google-chrome doxygen/html/index.html
```
> Zenoh documentation updates
