gazebosim/gz-transport

- .github/workflows/ci-bionic.yml
- CMakeLists.txt
- Changelog.md
- configure.bat
- docker/ign-transport/Dockerfile
As part of the works of https://github.com/ignition-tooling/gazebodistro/pull/5 bump the use of msgs to major version 6
> Update deps for Dome: use msgs6

- include/ignition/transport/Helpers.hh
- src/Node.cc
- src/NodeShared.cc
No warnings anymore! 
https://build.osrfoundation.org/job/ignition_transport-ci-pr_any-homebrew-amd64/827/
:green_salad:
> Remove warnings on Homebrew

- include/ignition/transport/TopicUtils.hh
- src/TopicUtils.cc
- src/TopicUtils_TEST.cc
Addresses https://github.com/ignitionrobotics/ign-gazebo/issues/239
Used by https://github.com/ignitionrobotics/ign-sensors/pull/33
Add a helper function to generate a valid topic name by converting spaces to `_` and stripping invalid character combinations.
> Helper function to get a valid topic name

- README.md
- tutorials/02_installation.md
This PR is related with this issue https://github.com/ignitionrobotics/docs/issues/14
Moved install instructions to the tutorials folder.
Signed-off-by: ahcorde <ahcorde@gmail.com>
> Removed repeated installation instructions

- log/src/Log.cc
- log/src/Recorder.cc
A topic could publish an Int32 or Int64 message with data=0. In this situation the protobuf message has size zero. While this is not a problem for protobuf messages, it is considered an error for SQLite3. 
Added logic to prevent console spamming.
> Prevent empty messages from spamming the console.

- src/NodeShared.cc
Fixing a small memory leak that I came across while profiling ign-gazebo.  Not sure if `sock` needs to be closed before that `return` call though, but since it was being done at the end of the function, I added it before the error-out `return` call as well.
> Fix mem leak

- tutorials/02_installation.md
* Use https for key download 57f47a8
* Update versions to modern ones 8b5ac8d
* Remove first person from instructions 4945d0d
* Update Windows: dependencies, Visual Studio and Windows versions 08c1df6
> Changes from Dome tutorial party

- CMakeLists.txt
- Changelog.md
Preparing for a last major version 7 release before Blueprint EOLs in 8 days.
Comparison to 7.5.0:
https://github.com/ignitionrobotics/ign-transport/compare/ignition-transport7_7.5.0...ign-transport7
There are no PRs open against `ign-transport7`.
> ⬆️  7.5.1 🏁

- CMakeLists.txt
- Changelog.md
> Prep for 8.2.0

- README.md
- tutorials/02_installation.md
Retargeting https://github.com/ignitionrobotics/ign-transport/pull/207 to Citadel.
> Add Windows Installation

- .github/workflows/ci.yml
- README.md
- bitbucket-pipelines.yml
Part of  https://github.com/ignition-tooling/release-tools/issues/416
Update all usage of `master`
> Master branch updates

- .github/ci/packages.apt
- CMakeLists.txt
- Migration.md
- docker/ign-transport/Dockerfile
- tutorials/02_installation.md
This is the new dependency part of #216
Add a dependency on the `cli` component of ignition-utils. This will be used to refactor the `ign` tool commands.
It should pass CI.
> Depend on cli component of ignition-utils

- Changelog.md
Preparation for 10.0.0~pre1 release.
Comparison to version 9: https://github.com/ignitionrobotics/ign-transport/compare/ign-transport9...main
The version in `CMakeLists` is already up-to-date.
> 🎈 10.0.0~pre1

- include/ignition/transport/Publisher.hh
- src/Publisher.cc
Targeting `main`, because I'm not sure if this breaks API.
We were defining copy and assignment operators that aren't necessary and broke rule of three/rule of five.
Signed-off-by: Michael Carroll <michael@openrobotics.org>
> Remove unnecessary copy and assignment operators

- include/ignition/transport/Helpers.hh
When building Debian packages for Debian/Buster I needed to use this patch to fix compilation. Seems like we were including the `4.3.1` to define the `IGN_ZMQ_POST_4_3_1` variable, which clearly seems to be a mistake.
>  Make zmq check for post 4.3.1 not to include 4.3.1

- include/ignition/transport/Discovery.hh
Fixes the following issue:
One publisher sets `IGN_IP` to `127.0.0.1` and advertises a topic with `Scope_T::Host`. With these settings, a default subscriber is unable to receive any messages.
The problem was that we were only checking if the source IP received was matching the host address used by the receiver. Now, we're checking if the source IP received matches any of the network interfaces or localhost.
To test (from the `examples` directory:
Terminal 1: `IGN_IP=127.0.0.1 ./publisher`
Terminal 2: `./subscriber`
- [] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
> Consider all network interfaces when checking HOST option.

- include/ignition/transport/TopicStatistics.hh
This PR is required by https://github.com/ignitionrobotics/ign-launch/pull/120
> Windows fix

- CMakeLists.txt
- Changelog.md
Preparation for 9.1.1 release.
Comparison to 9.1.1: https://github.com/ignitionrobotics/ign-transport/compare/ignition-transport9_9.1.0...ign-transport9
- [] Updated migration guide (as needed)
> 9 1 1 prep

- README.md
Signed-off-by: Louise Poubel <louise@openrobotics.org>
* https://github.com/ignitionrobotics/ign-tools/issues/8 has been fixed, now only https://github.com/ignitionrobotics/ign-tools/issues/61 is left.
* Update Windows badge
> 🥳  Update Windows badge and ign-tools issue on README

- tutorials/03_nodesAndTopics.md
Fixes minor typo in a tutorial.
The tutorial tells you that a topic containing a `@` isn't valid but the `@` wasn't rendered correctly.
> Fix typo in "nodes and topics" tutorial

- README.md
- example/bench.cc
- src/Discovery.cc
- src/NodeShared.cc
- src/NodeSharedPrivate.hh
- tutorials/02_installation.md
Signed-off-by: Alejandro Hernández <ahcorde@gmail.com>
Some fixes to improve macos support.
I'm not able to compile `publisher_custom_msg` and `subscriber_custom_msgs` because of this error:
```sh
msgs/stringmsg.pb.h:10:10: fatal error: 'google/protobuf/port_def.inc' file not found
#include <google/protobuf/port_def.inc>
```
any idea @scpeters ?
> tweaks documentation

- src/NetUtils.cc
This resolves a situation where gazebo is endlessly spamming:
```
Error getting username: no matching password record.
```
In our case, this triggered because a system was configured with ldap, but at runtime the `libnss_systemd` library wasn't available. This meant the user name lookup through ldap failed, and the fallback by reading it from `/etc/passwd` didn't work as the user wasn't present there. It can probably be reproduced by making the `getpwuid_r` always fail.
Basically, all this complexity can be removed by just checking the `$USER` environment variable. That is unlikely to fail on any linux system. I left the old behaviour in place as a fallback for if `USER` is not set, but I can't think of a situation where that would be.
**Note to maintainers**: Remember to use …
> Try USER variable to retrieve the username.

- src/cmd/ign.cc
- src/cmd/ign.hh
- src/cmd/ign_src_TEST.cc
- src/cmd/topic_main.cc
This adds a command line option `--json-output` to allow output in JSON format instead of Protobuf's default `DebugString` format. This would useful for manipulating message output with tools like `jq`. For example, if we wanted to extract just the `x` component of a `Pose` message, we could do
`ign topic -e --json-output -t /pose_topic | jq '.position.x'`
> Add option to output messages in JSON format

- .github/workflows/ci.yml
- include/ignition/transport/AdvertiseOptions.hh
- include/ignition/transport/CIface.h
- include/ignition/transport/Node.hh
- include/ignition/transport/NodeOptions.hh
- include/ignition/transport/NodeShared.hh
- include/ignition/transport/Publisher.hh
- include/ignition/transport/RepHandler.hh
- include/ignition/transport/ReqHandler.hh
- include/ignition/transport/TopicUtils.hh
- log/include/ignition/transport/log/MsgIter.hh
- log/include/ignition/transport/log/Playback.hh
- log/include/ignition/transport/log/QueryOptions.hh
- log/include/ignition/transport/log/SqlStatement.hh
- src/Publisher_TEST.cc
- tutorials/03_nodesAndTopics.md
- tutorials/21_contribute.md
Add `cppcheck`, `cpplint` and doxygen checks.
Focal CI on GitHub actions should return green.
> Focal CI: static checkers and doxygen linters

- src/cmd/cmdtransport.rb.in
See https://github.com/ignitionrobotics/ign-launch/pull/151
> Use exec instead of popen to run CLI11 based binaries

- .github/workflows/ci.yml
- Changelog.md
- include/ignition/transport/AdvertiseOptions.hh
- include/ignition/transport/CIface.h
- include/ignition/transport/Discovery.hh
- include/ignition/transport/Node.hh
- include/ignition/transport/NodeOptions.hh
- include/ignition/transport/NodeShared.hh
- include/ignition/transport/Publisher.hh
- include/ignition/transport/RepHandler.hh
- include/ignition/transport/ReqHandler.hh
- include/ignition/transport/TopicUtils.hh
- log/include/ignition/transport/log/MsgIter.hh
- log/include/ignition/transport/log/Playback.hh
- log/include/ignition/transport/log/QueryOptions.hh
- log/include/ignition/transport/log/SqlStatement.hh
- src/Discovery.cc
- src/NetUtils.cc
- src/NodeShared.cc
- src/Publisher_TEST.cc
- src/cmd/cmdtransport.rb.in
- src/cmd/ign.cc
- src/cmd/ign.hh
- src/cmd/ign_src_TEST.cc
- src/cmd/topic_main.cc
- tutorials/03_nodesAndTopics.md
- tutorials/20_env_variables.md
- tutorials/21_contribute.md
Port `ign-transport11` to `main`
Branch comparison: https://github.com/ignitionrobotics/ign-transport/compare/main...ign-transport11
> 11 ➡️ 12 (main)

- include/ignition/transport/Clock.hh
- log/test/integration/playback.cc
- log/test/integration/recorder.cc
- src/CMakeLists.txt
- src/cmd/ign_TEST.cc
* Part of https://github.com/ignition-tooling/release-tools/issues/685
`ign-cmake`'s utilities are deprecated, we should use `ign-utils` instead.
The main motivation for this PR though is that the latest transport debbuilds are failing because of `utilities`. The underlying reason is probably because we shouldn't be mixing `ign-cmake2` and `ign-cmake3`, or maybe because we're not releasing `ign-cmake3` correctly. In any case, this PR here is the right move and should fix the issue.
> Use ign-utils instead of ign-cmake utilities

- src/cmd/CMakeLists.txt
We are installing the cli11 binaries in under the standard library path which is something that does not fit well according to the [FHR](https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#usrlibexec). libexec seems a better place for them:
```
4.7.1. Purpose
/usr/libexec includes internal binaries that are not intended to be executed directly by users or shell scripts. Applications may use a single subdirectory under /usr/libexec.
```
> Use libexec to install lib binaries

- src/cmd/CMakeLists.txt
https://github.com/gazebosim/gz-transport/pull/279 updated the install directories to `libexec/` but the location variable wasn't updated. With a fresh fortress workspace, this caused `ign topic` and `ign service` to crash since it was looking in the wrong location: 
```bash
Traceback (most recent call last):
2: from /home/tuila/Workspaces/ignFortress/install/bin/ign:301:in
`<main>'
1: from
/home/tuila/Workspaces/ignFortress/install/lib/ruby/ignition/cmdtransport11.rb:43:in
`execute'
/home/tuila/Workspaces/ignFortress/install/lib/ruby/ignition/cmdtransport11.rb:43:in
``': No such file or directory -
/home/tuila/Workspaces/ignFortress/install/lib/ignition/transport11/ign-transport-topic
(Errno::ENOENT)
```
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit …
> Updated location variables to libexec

- CMakeLists.txt
- conf/CMakeLists.txt
- conf/transport.yaml.in
- include/gz/transport/CMakeLists.txt
- log/include/gz/transport/CMakeLists.txt
- log/src/CMakeLists.txt
- log/test/integration/CMakeLists.txt
- src/CMakeLists.txt
- src/cmd/CMakeLists.txt
- test/integration/CMakeLists.txt
- test/performance/CMakeLists.txt
- test/regression/CMakeLists.txt
* Part of https://github.com/gazebo-tooling/release-tools/issues/719
> [ign -> gz] CMake functions

- src/Node.cc
Cleans up two small warnings on clang/jammy combo: 
```
loop variable 'node' of type 'const std::pair<std::string, ISubscriptionHandler_M> &' (aka 'const pair<basic_string<char>, map<basic_string<char>, shared_ptr<gz::transport::ISubscriptionHandler>>> &') binds to a temporary constructed from type
```
The auto looks a little cleaner and prevents generating temporary copies in this context
> Use auto for loop iterators

- src/Discovery_TEST.cc
This test has recently appeared to fail, we have some on-going diagnosis in #335.  In the meantime, I think it makes sense to disable to get CI back into a reasonable state.
> Remove problematic discovery test

- src/Discovery_TEST.cc
Backport of #336 to Citadel
Signed-off-by: Michael Carroll <michael@openrobotics.org>
> [citadel] Backport "Remove problematic discovery test #(336)"

- include/ignition/transport/TopicStatistics.hh
Backport from https://github.com/gazebosim/gz-transport/pull/250 . We recently updated to ign-transport 8.3.0 on conda-forge, and in downstream tests (https://github.com/robotology/robotology-superbuild/issues/1242) we experienced a Windows error that was fixed in recent version of ign/gz-transport, but that was not fixed on the ign-transport8 branch.
Fix compilation problem in downstream projects.
> Backport Windows fix from main branch

- tutorials/23_topic_statistics.md
This pull request fixes a minor typo in the `topic statistics` tutorial. Our examples are under `example` and not under `examples`.
> Fix minor typo in topic statistics tutorial

- example/bench.cc
While going though the tutorials I noticed that the `bench` example doesn't compile. This patch should fix it.
> Fix bench example compilation

- tutorials/10_logging.md
The [logging tutorial](https://gazebosim.org/api/transport/12/logging.html) contains a section `Using gz for recording and playing back`. `gz` is sorrounded by backticks but it's not rendered properly. For now this pull request removes the backticks.
> Remove logging tutorial highlight

- tutorials/03_nodesAndTopics.md
The tutorial ["Nodes and Topics"](https://gazebosim.org/api/transport/12/nodestopics.html) uses two tables to show legal/ilegal topics and namespaces. The empty topics and namespaces are rendered as `</td>`. I'm trying this fix but not 100% sure if this will fix it.
Tagging @nkoenig in case he has extra tips.
> Fix table in "Nodes and topics tutorial"

- CMakeLists.txt
- Changelog.md
Preparation for <12.0.0> release.
Comparison to <11.2.0>: https://github.com/gazebosim/gz-transport/compare/ignition-transport11_11.2.0...gz-transport12
> Update Changelog for 12.0.0

- CMakeLists.txt
- include/ignition/transport/Helpers.hh
- include/ignition/transport/config.hh.in
Fixes #362
Presumably the versioning of cppzmq has the same problem on Debian Bullseye as on Ubuntu Focal.
This adds the same workaround for Debian Bullseye which seems to solve the build issue.
> Fix build for Debian Bullseye

- CMakeLists.txt
- Changelog.md
Preparation for 11.3.0~pre1 release.
Comparison to 11.2.0: https://github.com/ignitionrobotics/ign-transport/compare/ignition-transport11_11.2.0...ign-transport11
> Prepare for 11.3.0~pre1 Release

- CMakeLists.txt
- Changelog.md
Preparation for 8.4.0 release.
Comparison to  8.3.0: https://github.com/gazebosim/gz-transport/compare/ignition-transport8_8.3.0...ign-transport8
> 8.4.0 release

- conf/CMakeLists.txt
When `fortress` and `garden` are installed on the same system, there is a case where `ign topic` doesn't appear in the list of available commands for `fortress`, and `garden`'s `gz` command will not work with the error:
```
Configuration error: File [/usr/share/gz//transport12.yaml] contains a command already registered by ignition-transport.
```
It appears that somewhere in the forward porting of the renaming, we started erroneously installing `transport11.yaml` into the `/usr/share/gz` directory.  Specifically, the issue was introduced here (thanks @scpeters) https://github.com/gazebosim/gz-transport/commit/e31248efa946dab6efb83d674b1aac094955bdf7
This restores the installation location to the correct place.
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit …
> Fix CLI configuration install path to ignition

- CMakeLists.txt
- Changelog.md
Preparation for 12.1.0 release.
Comparison to 12.0.0: https://github.com/gazebosim/gz-transport/compare/gz-transport12_12.0.0...gz-transport12
> 12.1.0 release

- include/gz/transport/Node.hh
- src/Node.cc
- src/NodePrivate.hh
- src/NodeShared.cc
- src/NodeSharedPrivate.hh
- test/integration/CMakeLists.txt
- test/integration/callback_scope_TEST.cc
Fixes https://github.com/gazebosim/gz-transport/issues/380
This PR builds on top of the integration test in the `mjcarroll/callback_scope_test` branch and the test should now pass with these changes.
The fix is to loop through the publish queue and remove any outdated handlers that's responsible for invoking callbacks for the topic that's already been unsubscribed.
One important change that I need feedback on is the change of `pubQueue` from `std::queue` to `std::list`. This is done so that I can loop through the STL data structure
> Prevent invoking callbacks after a node unsubscribes to a topic

- include/gz/transport/Node.hh
- include/gz/transport/detail/Node.hh
Yes this does break API in a released version of transport. However, I believe it doesn't functionally change how `Node::Subscribe` operates, and should not affect downstream users.
The [Node::Subscribe](https://github.com/gazebosim/gz-transport/blob/ign-transport8/include/gz/transport/detail/Node.hh#L56) functions that take a `std::function` use pass by non-const reference. The provided `_cb` function is then copy-captured in a lambda function, or copied in [SubscriptionHandler::SetCallback](https://github.com/gazebosim/gz-transport/blob/ign-transport8/include/gz/transport/SubscriptionHandler.hh#L193).
Passing by value, which this PR proposes, has the same result as passing by reference. A copy is ultimately made.
You can read about …
> Pass std::function by value to Node::Subscribe

- include/gz/transport/Node.hh
- src/Node.cc
- src/cmd/gz.cc
- src/cmd/gz_TEST.cc
- src/cmd/gz_src_TEST.cc
- test/integration/twoProcsPubSub.cc
This patch includes the subscribed topics in the output of `gz topic -i`.
In one terminal run:
```
gz topic -e -t /foo
```
In another terminal run:
```
gz topic -i -t /foo
```
Your output should be:
```
No publishers on topic [/foo]
Subscribers [Address, Message Type]:
tcp://172.17.0.1:39133, google.protobuf.Message
```
> Show subscribers info when running topic info

- CMakeLists.txt
- Changelog.md
Preparation for 11.4.0 release.
Comparison to 11.3.2: https://github.com/gazebosim/gz-transport/compare/ignition-transport11_11.3.2...ign-transport11
Needed by https://github.com/gazebosim/gz-launch/pull/187
> 11.4.0 release

- test/test_config.hh.in
The current logic for choosing <filesystem> vs <experimental/filesystem> in tests is slightly wrong. For either clang toolchains with C++17 support or for gcc compiler >= 8, we should use the standard filesystem. In addition, this PR preserves the logic that if the system is not unix-like and also doesn't have a clang toolchain (e.g. windows), we should use the standard filesystem.
> Fix filesystem headers for tests

- CMakeLists.txt
- include/gz/transport/RepHandler.hh
- include/gz/transport/SubscriptionHandler.hh
Fix https://github.com/gazebosim/gz-transport/issues/404 by adding compatibility with protobuf >= 22 .
Similar to https://github.com/gazebosim/gz-msgs/pull/346, but with an additional fix to change the removed `google::protobuf::down_cast` to `google::protobuf::internal::DownCast` . It may not be ideal to use a function declared in an `internal::` namepsace, but that how actually the method was called in protobuf 2 when it was first used.
Install protobuf 22 or 23, and compile gz-citadel against it.
> Fix compatibility with protobuf 22

- CMakeLists.txt
- include/gz/transport/RepHandler.hh
- include/gz/transport/SubscriptionHandler.hh
- src/cmd/gz.cc
Part of https://github.com/osrf/homebrew-simulation/issues/2274. Cherry-picking forward to assist with rebuilding broken bottles.
Thanks to @traversaro for the patch!
Use rebase-and-merge.
> Cherry-pick #405 to garden: Fix compatibility with protobuf 22

- include/gz/transport/TopicStatistics.hh
Fixes a compilation problem in a downstream project: https://github.com/robotology/robotology-superbuild/issues/1425 by backporting https://github.com/gazebosim/gz-transport/pull/250 .
> Backport Windows fix to ign-transport8

- include/gz/transport/Discovery.hh
- log/test/integration/CMakeLists.txt
- log/test/integration/ign_log_record_force.rb
Fixes #400 
Discovery periodically sends topic/service heartbeats to keep all the topics/services advertised by a given node alive in the network. These messages are received by other discovery processes that keep the topics/services up to date or remove them in the absence of heartbeat updates after some time.
In order to get the list of topics/services, `gz` needs to initialize the discovery. This means that discovery should wait some time to receive all the topics/services updates to create the topic/service list. The original intent was to wait two cycles (2 * heartbeatInterval) before we consider the discovery initialized. However the current code only waits one cycle, as we were using the amount of  heartbeats sent as the condition. That's essentially one cycle, which wasn't the …
> Fix topic/service list inconsistency

- python/src/transport/_gz_transport_pybind11.cc
gz-transport callbacks are invoked from a separate thread so we need to acquire the GIL. Users such as gz-sim need to release the GIL regularly to ensure callbacks are serviced in a timely manner.
Came up in tests in https://github.com/gazebosim/gz-sim/pull/2081. Tests there are flaky without this PR.
> Acquire the GIL when invoking callbacks

- python/CMakeLists.txt
The `gz` directory was missing from the install path. The contents of the deb file before this PR is
```
/.
/usr
/usr/lib
/usr/lib/python3
/usr/lib/python3/dist-packages
/usr/lib/python3/dist-packages/transport13
/usr/lib/python3/dist-packages/transport13/__init__.py
/usr/lib/python3/dist-packages/transport13/_transport.cpython-310-x86_64-linux-gnu.so
/usr/share
/usr/share/doc
/usr/share/doc/python3-gz-transport13
/usr/share/doc/python3-gz-transport13/changelog.Debian.gz
/usr/share/doc/python3-gz-transport13/copyright
```
It should be `/usr/lib/python3/dist-packages/gz/transport13/`
Needed by https://github.com/gazebosim/gz-sim/pull/2081
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` …
> Fix python install directory

- include/gz/transport/Discovery.hh
See #430 
This patch fixes a potential race condition when calling `TopicList`.
See #430 to reproduce the issue/fix with the Gazebo `Image Display` plugin.
> Fix race condition in TopicInfo

- .github/workflows/triage.yml
- parameters/src/Client_TEST.cc
- parameters/src/cmd/ParamCommandAPI_TEST.cc
Port `gz-transport12 ` ➡️  `main`
Branch comparison: https://github.com/gazebosim/gz-transport/compare/main...gz-transport12
> Merge gz-transport12 ➡️  main

- CMakeLists.txt
- Changelog.md
Preparation for 11.4.1 release.
Comparison to 11.4.0: https://github.com/gazebosim/gz-transport/compare/ignition-transport11_11.4.0...ign-transport11
> Prepare for 11.4.1 Release

- README.md
Fixes https://github.com/gazebosim/gazebo_test_cases/issues/426
Fixes the links for the tutorial pages.
> Fixes tutorial links

- docker/gz-transport/Dockerfile
- tutorials/07_relay.md
Updates Dockerfile and fixes a minor issue in a tutorial.
Closes #<NUMBER>
Port <FROM_BRANCH> to <TO_BRANCH>
Branch comparison: https://github.com/gazebosim/<REPO>/compare/<TO_BRANCH>...<FROM_BRANCH>
Preparation for <X.Y.Z> release.
Comparison to <x.y.z>: …
> Fix Docker in Harmonic

- python/src/__init__.py
Any exception by a callback might cause a crash in gz-sim (see https://github.com/gazebosim/harmonic_demo/pull/14#discussion_r1334693934), so it's best to catch it here and print a traceback.
> Catch execeptions from callbacks since it might cause a crash 

- example/publisher.cc
- example/subscriber.cc
- tutorials/04_messages.md
- tutorials/05_services.md
- tutorials/07_relay.md
- tutorials/10_logging.md
- tutorials/23_topic_statistics.md
Fix the tutorial links to point to the Harmonic version.
> Fix Harmonic links in the tutorials

- CMakeLists.txt
- Changelog.md
Preparation for 13.0.0~pre2 release.
Comparison to gz-transport12: https://github.com/gazebosim/gz-transport/compare/gz-transport12...gz-transport13
> Prepare for 13.0.0~pre2 Release

- CMakeLists.txt
- Changelog.md
Preparation for 13.0.0 release.
Comparison to 13.0.0-pre2: https://github.com/gazebosim/gz-transport/compare/gz-transport13_13.0.0-pre2...gz-transport13
> Prepare for 13.0.0 Release

- .github/ci/packages.apt
- CMakeLists.txt
- docker/gz-transport/Dockerfile
- python/examples/data_race_with_mutex.py
- python/examples/data_race_without_mutex.py
- python/examples/publisher.py
- python/examples/requester.py
- python/examples/subscriber.py
- python/src/__init__.py
- python/test/options_TEST.py
- python/test/pubSub_TEST.py
- python/test/requester_TEST.py
- tutorials/02_installation.md
See https://github.com/gazebo-tooling/release-tools/issues/1027
> Bumps in ionic : ci_matching_branch/bump_ionic_gz-transport14

- src/cmd/transport.bash_completion.sh
This PR addresses the issue https://github.com/gazebosim/gz-tools/issues/1 regarding adding the third-level flags for `log` command.
```
$ . install/share/bash-completion/completions/ign
$ ign log r<tab> 
```
> Adds the third level commands for the log

- include/gz/transport/Node.hh
- src/Node.cc
I think this is actually what we intended to do with the `Node` constructor.
The `explicit` keyword makes using the default constructor a little strange in combination with `ImplPtr`.
For example:
```
class Foo
{
GZ_UTILS_UNIQUE_IMPL_PTR(dataPtr)
};
class Foo::Implementation
{
gz::transport::Node node;
};
```
Produces the compiler error:
```
In file included from /usr/local/google/home/mjcarroll/workspaces/gz_ionic/src/gz-gui/src/plugins/camera_tracking/CameraTracking.cc:18:
In file included from /usr/local/google/home/mjcarroll/workspaces/gz_ionic/install/include/gz/utils2/gz/utils/ImplPtr.hh:258:
/usr/local/google/home/mjcarroll/workspaces/gz_ionic/install/include/gz/utils2/gz/utils/detail/ImplPtr.hh:145:46: error: chosen constructor is explicit in copy-initialization
new …
```
> Make empty constructor as peer to explicit

- include/gz/transport/Discovery.hh
- src/Node_TEST.cc
Fixes #468 
As described in issue #468, the case of a `Request()` before an `Advertise()` when both calls are within the same process wasn't considered. This patch makes it work as in the case where requester and responser are in different processes (which was already working).
> Fix issue #468

- CMakeLists.txt
Motivated by https://github.com/gazebosim/gz-sim/issues/2249.
While testing the use of `-DPython3_EXECUTABLE=$(which python3)` to aid in finding the right version of python3 on macOS (see https://github.com/osrf/homebrew-simulation/pull/2543), I ran into some cmake configuration issues when testing locally (the bottle build seems to be progressing fine though). I was able to fix my local build by consolidating the logic for finding python3 by removing the use of gz-cmake's `GzPython` in favor of a single call to `find_package(Python3)`. This fixes setting `Python3_EXECUTABLE` to specify which python version to use and is needed on macOS.
As an aside, I'm going to suggest that we deprecate `GzPython` on `main` since it's better and simpler to just find python directly with modern versions …
> Find Python3 directly, not with GzPython

- CMakeLists.txt
PR #472 is a fix that will unbreak several CI jobs on macOS. It will be merged forward to main in #479, but that is slowed down by issues with commented tests, so I am cherry-picking this so expedite the fix of CI.
Commit message:
> This removes the use of gz-cmake's GzPython in favor of a single call to find_package(Python3). This allows setting Python3_EXECUTABLE to specify which python version to use and is needed on macOS.
**Note to maintainers**: Remember to use **Rebase-and-Merge**.
> Cherry-pick #472 to main: Find Python3 directly, not with GzPython

- src/cmd/gz_TEST.cc
- src/cmd/service_main.cc
Fixes #475
This patch makes the timeout optional when requesting services from the command line.
Compile the transport examples and run:
```
./responser
```
And then type in a separate terminal:
```
gz service -s /echo --reqtype gz.msgs.StringMsg --reptype gz.msgs.StringMsg --req 'data: "Hello"'
```
You should receive:
```
data: "Hello"
```
> Use a default timeout when requesting a service from CLI.

- src/cmd/gz_TEST.cc
- src/cmd/service_main.cc
Fixes #97 and #474
This patch makes it possible to request a no input service request from the command line. Before, it was possible passing `--reqtype gz.msgs.Empty` but always adding the `--req 'unused: true'`
You can compile the examples, and then:
1. Launch the no-input responser:
```
./responser_no_input
```
2. Request the service using the "old" way:
```
gz service -s /quote --reqtype gz.msgs.Empty --reptype gz.msgs.StringMsg -r 'unused:true'
```
3. Use the new no-input request and verify that you still get a reply:
```
gz service -s /quote --reptype gz.msgs.StringMsg -r
``` 
Note that both requests should reach the responser and you should get a reply on the requester terminal:
```
data: "This is it! This is the answer. It says here...that a bolt of lightning is going to strike the …
```
> No input service request from the command line

- CMakeLists.txt
- Changelog.md
Preparation for 13.2.0~pre1 release.
Comparison to 13.1.0: https://github.com/gazebosim/gz-transport/compare/gz-transport13_13.1.0...prep_13.2.0pre1
> Prepapre for 13.2.0 prerelease

- include/gz/transport/NodeShared.hh
- log/src/Recorder.cc
- src/Node.cc
- src/NodePrivate.hh
- src/NodeShared.cc
#484 fixed the `INTEGRATION_triggered_publisher` test in gz-sim8, but introduced a couple of regressions (see https://build.osrfoundation.org/job/gz_sim-ci-gz-sim8-jammy-amd64/82/ and https://build.osrfoundation.org/job/gz_sim-ci-gz-sim8-jammy-amd64/83/):
**NetworkHandshake.Updates**
```
Error Message
/home/jenkins/workspace/gz_sim-ci-gz-sim8-jammy-amd64/gz-sim/test/integration/network_handshake.cc:220
Expected: (100u) <= (zPos.size()), actual: 100 vs 70
```
and **ServerRepeat/SceneBroadcasterTest.StateStatic/0 (from ServerRepeat_SceneBroadcasterTest)**
```
Error Message
/home/jenkins/workspace/gz_sim-ci-gz-sim8-jammy-amd64/gz-sim/test/integration/scene_broadcaster_system.cc:588
Expected: (stepMsg.stats().real_time().nsec()) < (_msg.stats().real_time().nsec()), actual: 943661800 vs …
```
> Revert "Use `std::shared_ptr` for `gz::transport::NodeShared` (#484)"

- conf/CMakeLists.txt
- log/src/cmd/CMakeLists.txt
- parameters/src/cmd/CMakeLists.txt
- src/cmd/CMakeLists.txt
Fixes an error when building https://github.com/gazebo-release/gz_transport_vendor/ in the ROS buildfarm.
Similar to https://github.com/gazebosim/gz-tools/pull/137
> Use relative install path for gz tool data

- CMakeLists.txt
- Changelog.md
Preparation for 13.2.0 release.
Comparison to 13.1.0: https://github.com/gazebosim/gz-transport/compare/gz-transport13_13.1.0...azeey:prep_13.2.0
> Prepare for 13.2.0

- .github/ci/packages.apt
- package.xml
Similar to https://github.com/gazebosim/gz-sim/pull/2374
> Remove python3-distutils since it's not needed on Jammy

- tutorials.md.in
The python tutorial is missing from the list in https://gazebosim.org/api/transport/13/tutorials.html
> Include Python tutorial in list of tutorials

- .github/ci/packages.apt
Should fix debbuilders not finding distutils dependency on main for Noble.
Reference build: https://build.osrfoundation.org/job/gz-transport14-debbuilder/310/
Removing distutils dependency, forward port differs a bit from original PR because in gz-transport13 there is a package.xml not available in main yet.
> (Forward port) Remove python3-distutils since it's not needed on Jammy (#496)

- log/include/gz/transport/log/Batch.hh
Fixes rule-of-five violation and reduces flakiness of playback tests.
> Delete copy ctor and copy-assignment for log::Batch

- include/gz/transport/Discovery.hh
- include/gz/transport/Node.hh
- include/gz/transport/NodeShared.hh
- src/Node.cc
- src/NodeShared.cc
- src/Node_TEST.cc
This change allows users to configure relays from code without having to `setenv(GZ_RELAY)`.
This change allows users to configure relays from code without having to `setenv(GZ_RELAY)`.
Supersedes https://github.com/gazebosim/gz-transport/pull/497
This can be tested by starting a Node across a boundary where multicast isn't enabled, and setting the relay IP via NodeOptions.
> Allow programmatic configuration of unicast relays.

- .github/workflows/ci.yml
- CMakeLists.txt
- example/CMakeLists.txt
- python/CMakeLists.txt
Part of https://github.com/gazebosim/gz-cmake/issues/350.
This adds a GitHub workflow using Noble and increases our minimum required cmake version to 3.22.1 since we are already requiring that in gz-cmake4. It also removes some old code to support older versions of cmake.
Look at the 24.04 CI results.
> Enable 24.04 CI, require cmake 3.22.1

- include/gz/transport/SubscribeOptions.hh
- include/gz/transport/SubscriptionHandler.hh
- src/Node.cc
- src/NodeShared.cc
- src/NodeSharedPrivate.hh
- src/Node_TEST.cc
- src/SubscribeOptions.cc
- src/SubscribeOptionsPrivate.hh
- src/SubscriptionHandler.cc
Adds a new option to ignore local messages (when publisher and subscriber share the same node).
Some context [here](https://github.com/gazebosim/ros_gz/issues/555) .
> Adding option to ignore local messages

- .github/workflows/package_xml.yml
- Changelog.md
- include/gz/transport/SubscribeOptions.hh
- include/gz/transport/SubscriptionHandler.hh
- package.xml
- src/Node.cc
- src/NodeShared.cc
- src/NodeSharedPrivate.hh
- src/Node_TEST.cc
- src/SubscribeOptions.cc
- src/SubscribeOptionsPrivate.hh
- src/SubscriptionHandler.cc
- src/cmd/gz.cc
- src/cmd/gz.hh
- src/cmd/topic_main.cc
- tutorials.md.in
Port gz-transport13 to main
Branch comparison: https://github.com/gazebosim/gz-transport/compare/main...gz-transport13
> Merge 13 -> main

- .github/ci/packages-noble.apt
- .github/ci/packages.apt
In Jammy, the zmq C++ headers were included in libzmq-dev. However, in Noble, the headers are now in a separate package, `cppzmq-dev`, and that package is recommended by libzmq-dev. This shouldn't affect most users, but anywhere these dependencies are installed with `--no-install-recommends` will now break because it won't have cppzmq-dev installed. This patch just adds an explicit dependency to avoid the problem.
> Add an explicit dependency on cppzmq-dev

- log/test/integration/playback.cc
Disables #195 
This tests has been failing flaky for a really long time. As discussed in Gazebo PMC meeting, this test will be disabled.
> Disable playback.ReplayStep for windows

- tutorials/06_python_support.md
…rt13
Fixes #511 
Added Prerequisites section specifying to install the required library
> Added Prerequisites section in file

- log/test/integration/playback.cc
Port ign-transport11 to gz-transport12
Follow up of #517, #518 
Disables #195
Branch comparison: https://github.com/gazebosim/gz-transport/compare/ign-transport12...ign-transport11
> 11 :arrow_right: 12 - Disable playback.ReplayStep for windows (#517)

- log/test/integration/playback.cc
Port ign-transport12 to gz-transport13
Follow up of #517, #518, #521
Disables #195
Branch comparison: https://github.com/gazebosim/gz-transport/compare/gz-transport13...gz-transport12
> 12 :arrow_right: 13 - Disable playback.ReplayStep for windows (#517)

- Changelog.md
- README.md
Part of https://github.com/gazebo-tooling/release-tools/issues/1092
> Update gz-transport14 badge URLs

- CMakeLists.txt
- Changelog.md
Preparation for 14.0.0~pre1 release.
Comparison to 13.4.0: https://github.com/gazebosim/gz-transport/compare/gz-transport13_13.4.0...prep_14.0.0pre1
> Prepare for 14.0.0~pre1 release

- tutorials/01_intro.md
It fixes two links issues in the tutorial. You can see the two incorrect links [here](https://gazebosim.org/api/transport/14/introduction.html).
> Fix installation tutorial links

- tutorials/02_installation.md
Fixes minor issues in the [Installation tutorial](https://gazebosim.org/api/transport/14/installation.html).
> Ionic: Installation tutorial fixes

- example/playback.cc
- example/record.cc
- log/src/cmd/cmdlog.rb.in
- tutorials/10_logging.md
While testing the [logging tutorial ](https://gazebosim.org/api/transport/14/logging.html), I ran into an issue executing:
```
gz log record --force --file tutorial.tlog
```
The ruby `File.exists()` function was removed in `3.2.0`, which is the version in Ubuntu Noble. I updated the code and also used `snippet` in the tutorial.
> Replace deprecated ruby File.exists with File.exist and tweak tutorial

- tutorials/04_messages.md
- tutorials/06_python_support.md
- tutorials/07_security.md
- tutorials/10_logging.md
- tutorials/23_topic_statistics.md
Added a notice about GZ_PARTITON to all relevant tutorials.
> tutorials: Added notices about GZ_PARTITION

- tutorials/05_services.md
Fixes https://github.com/gazebosim/gazebo_test_cases/issues/1542
Improved a few commandlines to include Windows instructions.
Added a notice about GZ_PARTITION, which is often problematic on Windows.
Added a notice about firewall prompts.
> tutorials/05_services: Windows improvements

- tutorials/23_topic_statistics.md
Tested in https://github.com/gazebosim/gazebo_test_cases/issues/1566
> Windows fixes for statistics tutorial

- CMakeLists.txt
- Changelog.md
Preparation for 14.0.0 release.
Comparison to 14.0.0-pre1: https://github.com/gazebosim/gz-transport/compare/gz-transport14_14.0.0-pre1...gz-transport14
> Prepare for 14.0.0 release

- log/test/integration/playback.cc
Port `gz-transport13` to `gz-transport14`
Branch comparison: https://github.com/gazebosim/gz-transport/compare/gz-transport14...claraberendsen:claraberendsen/13_to_14_2024-10-01
Follow up of https://github.com/gazebosim/gz-transport/pull/517, https://github.com/gazebosim/gz-transport/pull/518, https://github.com/gazebosim/gz-transport/pull/521, #522 
Disables https://github.com/gazebosim/gz-transport/issues/195
>  Disable playback.ReplayStep for windows (#517)

- CMakeLists.txt
- Changelog.md
- example/CMakeLists.txt
- package.xml
- python/examples/data_race_with_mutex.py
- python/examples/data_race_without_mutex.py
- python/examples/publisher.py
- python/examples/requester.py
- python/examples/subscriber.py
- python/src/transport/_gz_transport_pybind11.cc
- python/test/options_TEST.py
- python/test/pubSub_TEST.py
- python/test/requester_TEST.py
- tutorials/04_messages.md
- tutorials/05_services.md
- tutorials/06_python_support.md
- tutorials/08_relay.md
- tutorials/10_logging.md
- tutorials/23_topic_statistics.md
Bump main to gz-transport 15.0.0~pre1
> Bump main to gz-transport 15.0.0~pre1

- src/cmd/cmdtransport.rb.in
Part of https://github.com/gazebosim/gz-tools/issues/7
As suggested in this [comment](https://github.com/gazebosim/gz-tools/issues/7#issuecomment-2392071709) by @scpeters, porting the fix from https://github.com/gazebosim/gz-plugin/pull/131 for determination of absolute path in ruby script. 
> Using Pathname to check for absolute path in ruby script

- include/gz/transport/RepHandler.hh
- include/gz/transport/SubscriptionHandler.hh
Adds compatibility with the Google Protocol Buffers v28.
Basically, rules for message down casting have been changed in protobuf and this PR modifies the way protobuf is used for downcasting.
Protobuf does not allow to use google::protobuf::internal::DownCast function to downcast message types with concepts enabled in version 28 (see port.h file in [this](https://github.com/protocolbuffers/protobuf/commit/e0690ce6c7b97ca2fe89f23f363d549764a0fc39#diff-ae1dc11d096fc98a5d3ab8a8c1bdac8b004433aa350c39a11348600d44308dcdR165) diff). When compiling custom packages which depend on the gz-transport with C++ concepts enabled, there will be compile-time errors, if RepHandler::RunLocalCallback or SubscriptionHandler::RunLocalCallback functions were used (not necessarily used directly, but via some …
> Add compatibility with protobuf 28

- src/cmd/gz_TEST.cc
Fixes #510 
The flakiness appears to be a timing issue. The fix here involves running the loop that waits for the input messages in a separate thread before starting the publisher.
> Fix flakiness in the TopicInfo test

- tutorials/06_python_support.md
Port `gz-transport13 ` ➡️  `gz-transport14`
Branch comparison: https://github.com/gazebosim/gz-transport/compare/gz-transport14...gz-transport13
> Merge gz-transport13 ➡️  gz-transport14

- CMakeLists.txt
Unhides a cmake warning when python bindings will not be built
A cmake warning should be printed when python bindings will not be built (controlled by the logic around `add_subdirectory(python)`), but the warning was in a separate part of the code, allowing the warning to be missed if the `Python3_Development_FOUND` variable changed in between.
Since `GZ_BUILD_WARNING("")` only generates a cmake warning if invoked before `gz_configure_build`, I switched to use `message(WARNING "")` in https://github.com/gazebosim/gz-transport/pull/565/commits/e464330418197347b4ce208be354864405cf5779.
Also, the failed Ubuntu Noble CI build is expected because finding python is currently broken for all platforms, but only our Ubuntu Noble CI builds report cmake warnings. I believe finding python should be …
> Unhide cmake warning when Python3 Development is not found

- CMakeLists.txt
- Changelog.md
Preparation for 8.5.1 release.
Comparison to 8.5.0: https://github.com/gazebosim/gz-transport/compare/ignition-transport8_8.5.0...ign-transport8
Part of https://github.com/gazebo-tooling/release-tools/issues/1252
> Prepare for 8.5.1 Release

- src/Node.cc
- src/NodeShared.cc
- test/CMakeLists.txt
- test/integration/CMakeLists.txt
- test/integration/test_executables/twoProcsPubSubSingleSubscriber_aux.cc
- test/integration/twoProcsPubSub.cc
- test/test_config.hh.in
Fixes https://github.com/gazebosim/gz-transport/issues/586
The bug happens because the publisher is no longer available when the subscriber unsubscribes. No message is then sent to the publisher node for it to remove the remote subscribers.
The fix:  If the publisher is not available when a subscriber unsubscribes, a message with empty publisher proc address is now sent to all nodes on the network, which forces the publisher nodes to check and remove the remote subscriber if it exists.
> Remove subscribers after publisher ends

- log/test/integration/CMakeLists.txt
- python/CMakeLists.txt
- src/CMakeLists.txt
- src/cmd/CMakeLists.txt
- test/integration/CMakeLists.txt
Fixes recent test failures on homebrew
Firewall settings can cause test failures, so set `GZ_IP` explicitly to make tests more hermetic.
> Set GZ_IP=127.0.0.1 in tests needing network

- python/CMakeLists.txt
Fixes build errors with cmake 4.0
The cmake version in homebrew-core was recently upgraded to 4.0, which now requires `cmake_minimum_required` to be set (see [policy CMP0000](https://cmake.org/cmake/help/latest/policy/CMP0000.html)). We currently support building python bindings separately from the core library by invoking cmake directly on `python/CMakeLists.txt`, so add support for cmake 4.0 by adding a `cmake_minimum_required` statement to `python/CMakeLists.txt`.
> Support cmake 4.0

- python/CMakeLists.txt
Simplifies the cmake code
Since adding the `cmake_minimum_required` statement to the top of `python/CMakeLists.txt` in #603, we can remove the duplicate statement a few lines after. I would have removed it in #603, but didn't notice it.
> Remove duplicate cmake_minimum_required

- log/src/QueryOptions.cc
When `GetTime()->count()` doesn't return `int64_t`, unambiguously select `SqlParameter(int64_t _integer)`.
Fixes a build error with 64 bit android (clang).
(The choice is between int64_t and double. The input is an integer, typically an int64_t.)
The following problem was discovered for x64 and arm64 android while reviewing the vcpkg port:
~~~
/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/__memory/allocator.h:165:24: error: call to constructor of 'gz::transport::log::SqlParameter' is ambiguous
165 |     ::new ((void*)__p) _Up(std::forward<_Args>(__args)...);
|                        ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/__memory/allocator_traits.h:296:9: note: in instantiation …
> Cast nanoseconds to int64_t

- .github/workflows/ci.yml
- log/include/gz/transport/log/MsgIter.hh
Jetty on Jammy is not officially supported 
Made a small doxygen fix for CI to pass on noble
> Disable Jammy CI

- .github/workflows/ci.yml
- log/include/gz/transport/log/MsgIter.hh
Part of https://github.com/gazebo-tooling/release-tools/issues/1222
Jammy isn't officially supported for Ionic, so move linters to use Noble.
Includes a small fix for a doxygen complaint.
> ci: run cppcheck, cpplint, doxygen on noble

- include/gz/transport/RepHandler.hh
- include/gz/transport/ReqHandler.hh
- include/gz/transport/SubscriptionHandler.hh
- include/gz/transport/detail/Node.hh
- parameters/src/Client.cc
- parameters/src/Registry.cc
- src/CIface_TEST.cc
- src/HandlerStorage_TEST.cc
- src/Node.cc
- src/Node_TEST.cc
- src/cmd/gz.cc
- src/cmd/gz_TEST.cc
- test/integration/test_executables/twoProcsPubSubSingleSubscriber_aux.cc
- test/integration/test_executables/twoProcsPubSubSubscriber_aux.cc
- test/integration/twoProcsPubSub.cc
Fix compatibility with protobuf v30 (cpp 6.30.0) - similar to gz-msgs #499
- [x ] Signed all commits for DCO
- [ n/a] Added tests
- [ n/a] Updated documentation (as needed)
- [ n/a] Updated migration guide (as needed)
- [ n/a] Consider updating Python bindings (if the library has them)
- [ x] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
Closes #<NUMBER> …
> Fix compatibility with protobuf v30 (cpp 6.30.0) - similar to gz-msgs #499

- .github/ci/before_cmake.sh
- .github/ci/packages-noble.apt
- CMakeLists.txt
Related PR:
* https://github.com/gazebo-tooling/gzdev/pull/96
* https://github.com/gazebo-tooling/release-tools/pull/1311
If upstream zenohc and zenohcpp packages are not found, try look for zenoh_cpp_vendor packages from the ros2 repo
Tested with `ros-rolling-zenoh-cpp-vendor` package on noble and gz-transport is able to find zenohc and zenohcxx with this package.
> Find zenoh_cpp_vendor package from ROS 2

- .github/ci/before_cmake.sh
- .github/ci/packages-noble.apt
- CMakeLists.txt
- include/gz/transport/Node.hh
- include/gz/transport/config.hh.in
- log/src/CMakeLists.txt
- log/test/integration/CMakeLists.txt
- parameters/src/CMakeLists.txt
- python/CMakeLists.txt
- src/CMakeLists.txt
- src/cmd/CMakeLists.txt
- test/integration/CMakeLists.txt
This patch should define `HAVE_ZENOH` if the zenoh dependencies are found at compile time.
> Zenoh - Part1: Find Zenoh and define HAVE_ZENOH when found

- Migration.md
- include/gz/transport/Node.hh
- include/gz/transport/NodeShared.hh
- include/gz/transport/detail/Node.hh
- src/Node.cc
- src/NodePrivate.hh
- src/NodeShared.cc
- src/NodeSharedPrivate.hh
- src/Node_TEST.cc
- test/CMakeLists.txt
- test/integration/CMakeLists.txt
- test/integration/test_executables/twoProcsPubSubMixedSubscribers_aux.cc
- test/integration/twoProcsPubSub.cc
- test/test_config.hh.in
Backport the new `Node::CreateSubscriber` API function added in #608.
This PR does not backport the refactoring of the `Node::Subscribe` functions as that introduces a break change as mentioned in https://github.com/gazebosim/gz-sim/pull/2894
> Backport Node::CreateSubscriber API

- include/gz/transport/Node.hh
- src/Node.cc
- src/NodeShared.cc
- src/Node_TEST.cc
Add move constructor / assignment operator to fix unintended topic unsubscription when following code is used to create a `Node::CreateSubscriber`:
```cpp
gz::transport::Node::Subscriber sub;
sub = node.CreateSubscriber(g_topic, subCb);
```
The above call invokes the move assignment operator. The tmp `Node::Subscriber` object returned by `CreateSubscriber` is destroyed causing it to call `Unsubscribe` in its destructor, which unintentionally removes the subscription handler from `NodeShared`. As the result the new `sub` object is never able to receive any messages.
This PR overrides the assignment operator to invalidate the `Node::Subscriber` object that is being moved so that it does not unsubscribe itself when destroyed.
I also ported the change that I made in …
> Add move constructor / assignment operator to Node::Subscriber

- .github/workflows/bazel.yml
- MODULE.bazel
This fixes clang build under `--copt=-Werror --per_file_copt=+external/.*@-Wno-everything`. Verified with
```
$ bazel build --copt=-Werror --per_file_copt=+external/.*@-Wno-everything --action_env=CC=/usr/bin/clang :all
```
The `--per_file_copt` setting excludes warnings from external dependencies from causing build failure. However, `libzmq` in particular uses `rules_foreign_cc:cmake` to build, which does not respect the `--per_file_copt` setting. There was one error from `-Wmissing-braces` in `libzmq` that was fixed in [BCR ](https://github.com/bazelbuild/bazel-central-registry/pull/4630).
This PR updates the `libzmq` dep version to fix the build.
Also requires in a version bump for bazel-contrib/.github/.github/workflows/bazel.yaml which we use for bazel CI since there is an error with …
> [Bazel] Bump libzmq dep to 4.3.5.bcr.3

- parameters/src/Client_TEST.cc
Part of https://github.com/gazebosim/gz-transport/issues/435.
While fixing https://github.com/gazebosim/gz-transport/issues/435, it was hard to identify the reason for failures in the parameters `Client_TEST`. This checks the return value of more API calls and prints the `ParameterResult` value when test expectations fail to provide diagnostic info for debugging.
There are several places where `ParameterResult` values are stored in variables named `ret`, and for consistency, I renamed these variables to `result`.
> parameters Client_TEST: check more APIs, more error output

- Migration.md
- parameters/src/Client.cc
- parameters/src/Client_TEST.cc
- parameters/src/Registry.cc
- parameters/src/Registry_TEST.cc
- parameters/src/Utils.cc
- parameters/src/Utils.hh
- parameters/src/Utils_TEST.cc
Follow-up to https://github.com/gazebosim/gz-transport/pull/647.
The use of non-qualified message names was removed from the parameters component in https://github.com/gazebosim/gz-transport/pull/647, some of which involved keeping `gz.msgs` namespaces instead of replacing them with `gz_msgs`. This goes further for consistency, using `gz.msgs` instead of `gz_msgs` in all parts of the `parameters` component, including removal of the helper function that prepends message types with `gz_msgs` and instead using the full name of descriptors.
Check CI
> parameters: use gz.msgs instead of gz_msgs

- Migration.md
- include/gz/transport/RepHandler.hh
- include/gz/transport/SubscriptionHandler.hh
- include/gz/transport/TopicUtils.hh
- include/gz/transport/TransportTypes.hh
- include/gz/transport/detail/Node.hh
- src/Discovery.hh
- src/HandlerStorage_TEST.cc
- src/Node.cc
- src/NodeShared.cc
- src/RepHandler.cc
- src/SubscriptionHandler.cc
- src/TopicUtils.cc
- src/TopicUtils_TEST.cc
Adds Zenoh graph cache support for async services.
Compile the examples and run a service provider:
```
GZ_TRANSPORT_IMPLEMENTATION=zenoh ./responser
```
and
```
GZ_TRANSPORT_IMPLEMENTATION=zenoh gz service -l
```
You should see the service `/echo`.
You can repeat the previous examples replacing `zenoh` with `zeromq` to verify that nothing is broken.
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.**
> Zenoh - Part 5: Implement graph cache for async services

- src/Discovery.hh
- src/NodeShared.cc
- src/Node_TEST.cc
- test/integration/twoProcsPubSub.cc
This PR removes some hardcoded block that was telling gz transport that there was always a remote subscriber. It enables most of the pub/sub tests.
The tests should pass.
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.**
> Zenoh - Part 7: Enable pub sub tests and remove hardcoded block

- .vscode/settings.json
- parameters/src/cmd/ParamCommandAPI.cc
Fixes #661 
You can reproduce the crash according to #661 
Before the fix: gazebo crashes with a stack trace.
After the fix: gazebo prints a user-friendly error message and exits without crashing.
> BugFix :  Failure to catch after throwing an error causes a crash

- .github/workflows/ci.yml
- CMakeLists.txt
Adds a cmake option, `GZ_TRANSPORT_ENABLE_ZENOH`, for disabling building the zenoh implementation. The variable is `ON` by default (zenoh will be built if available).
We currently have 2 noble github ci actions
* `Ubuntu Noble CI`: Builds gz-transport with zeromq and zenoh. Runs tests using **zeromq**
* `Ubuntu Noble CI -Zenoh`: Builds gz-transport zeromq and zenoh. Runs tests using **zenoh**
I updated the `Ubuntu Noble CI` job to disable building gz-transport with zenoh by setting `GZ_TRANSPORT_ENABLE_ZENOH=OFF` so that we can catch build errors when zenoh is not available.
See example [github action runs](https://github.com/gazebosim/gz-transport/actions/runs/16331997700). In the `Ubuntu Noble CI` build, cmake no longer tries to find zenoh and continues building gz-transport with zeromq …
> Add cmake option to disable building gz-transport with zenoh

- include/gz/transport/detail/Node.hh
There scope of the mutex lock is unnecessarily large which causes deadlocks in service requests when running local callbacks. This PR uses the same approach as the `Node::Request` shown below to reduce the scope of the mutex:
https://github.com/gazebosim/gz-transport/blob/68a3fb272aa2ca16e037e85940441e5b6be85779/include/gz/transport/detail/Node.hh#L427-L466
> Fix deadlock in service requests when running local callbacks

- test/integration/test_executables/twoProcsPubSubMixedSubscribers_aux.cc
https://github.com/gazebosim/gz-transport/pull/615 fixed compatibility with protobuf v30, but https://github.com/gazebosim/gz-transport/pull/608 reintroduced an incompatibility, that is fixed by this PR.
> Fix compatibility with protobuf v30 (cpp 6.30.0) regression

- src/Helpers_TEST.cc
Fixes a recent [test failure](https://build.osrfoundation.org/job/gz_transport-main-cnlwin/37/testReport/(root)/HelpersTest/TransportImplementation/) on Windows.
> Fix Helpers_TEST on windows

- BUILD.bazel
This should fix the bazel build in the gz-sim's [9 -> main forward merge](https://github.com/gazebosim/gz-sim/pull/3030) as it complains about missing headers.
> [Bazel] Update gz-discovery-header deps

- include/gz/transport/TopicStorage.hh
- src/Discovery.hh
- test/integration/twoProcsPubSub.cc
Fixes  `twoProcPubSub.TopicInfo` and `twoProcPubSub.PubSubTwoProcsScopedPub` tests.
As described in #681,  `twoProcPubSub.TopicInfo`: `Node::TopicInfo` returned more publishers than expected. We weren't properly removing the publishers from the data structure because the topic wasn't correctly formed.
In `twoProcPubSub.PubSubTwoProcsScopedPub`,  `Publisher::HasConnections` was returning an unexpected true. This was a wrong assumption in the test, because the remote subscriber is already registered in the network (Zenoh) before the call to `Advertise()`. 
> Enable more zenoh tests on twoProcsPubSub.cc

- src/NodeShared.cc
- src/NodeSharedPrivate.hh
This patch instantiates the Zenoh session only when it's needed (when setting GZ_TRANSPORT_IMPLEMENTATION=zenoh).
You can use `gdb` to launch gz-sim server:
```
GZ_TRANSPORT_IMPLEMENTATION=zeromq gdb ./install/libexec/gz/sim10/gz-sim-server
r shapes.sdf
```
Then, `CTRL-C` the simulation, and check the running threads:
```
thread all apply bt
```
You shouldn't see any threads related with `zenoh`.
> Instantiate zenoh session only if needed

- .github/ci/before_cmake.sh
- .github/ci/packages-noble.apt
- .github/workflows/ci.yml
Switch to use the zenoh packages for packages.osroundation.org instead of using zenoh-cpp-vendor from ros repo
[github actions test builds](https://github.com/gazebosim/gz-transport/actions/runs/17245229762) are green
Related release-tools PR for jenkins noble build: https://github.com/gazebo-tooling/release-tools/pull/1384
> Install zenoh packages from packages.osrfoundation.org

- BUILD.bazel
- MODULE.bazel
- src/TopicUtils_TEST.cc
Enable unit tests in bazel build that were previously disabled due to missing gz-common bazel build.
> [bazel] Enable unit tests

- CMakeLists.txt
- Changelog.md
Preparation for 15.0.0 release.
Comparison to 15.0.0~pre2: https://github.com/gazebosim/gz-transport/compare/gz-transport15_15.0.0-pre2...gz-transport15
> Prepare for 15.0.0 release

- src/Node.cc
- src/Node_TEST.cc
Fixes #717 
Properly initializes the move constructor.
> Initialize move constructor
